api/urls.py
from django.urls import path
from rest_framework import routers
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from rest_framework_simplejwt.serializers import TokenObtainPairSerializer

from api.viewsets import AthleteViewSet, TeamViewSet

app_name = "Api"


class ApiTokenObtainPairSerializer(TokenObtainPairSerializer):
    def validate(self, attrs):
        data = super().validate(attrs)
        data["username"] = self.user.username

        return data


class ApiTokenObtainPairView(TokenObtainPairView):
    """
    Takes a set of user credentials and returns username and an access and refresh JSON web
    token pair to prove the authentication of those credentials.
    """

    serializer_class = ApiTokenObtainPairSerializer


urlpatterns = [
    path("token", ApiTokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh", TokenRefreshView.as_view(), name="token_refresh"),
]


# Routers provide a way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r"athletes", AthleteViewSet)
router.register(r"teams", TeamViewSet)

athletes/urls.py
"""
Athletes URL Configuration
"""

from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.utils.translation import gettext_lazy as _

from api.urls import router


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("api/", include("api.urls", namespace="api")),
    path("api/", include(router.urls)),
    path("stripe/", include("djstripe.urls", namespace="djstripe")),
    path("admin/", admin.site.urls),
]

admin.site.site_header = _("Athletes administration")


if settings.DEBUG:
    from django.conf.urls.static import static
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

core/urls.py
from django.urls import path

from core.views.api import (
    athletes_export_api,
    athletes_list_api,
    add_athlete_to_lists_api,
    add_team_to_lists_api,
    add_league_to_lists_api,
    follow_api,
    autocomplete_api,
)
from core.views.pages import (
    athletes_page,
    about_page,
    login_page,
    logout_page,
    ParseTeamView,
    ParseLeagueView,
    athlete_page,
    terms_page,
    map_page,
    team_page,
    league_page,
    country_page,
    ProfileView,
    compare_athletes_page,
    teams_page,
)

app_name = "Athletes"

urlpatterns = [
    path("", about_page, name="home"),
    path("athletes", athletes_page, name="athletes"),
    path("teams", teams_page, name="teams"),
    path("athletes_list", athletes_list_api, name="athletes_list"),
    path("athlete/<str:slug>", athlete_page, name="athlete"),
    path("compare/athletes", compare_athletes_page, name="compare_athletes"),
    path("api/athletes_list", add_athlete_to_lists_api, name="athletes_list"),
    path("team/<int:pk>", team_page, name="team"),
    path("league/<int:pk>", league_page, name="league"),
    path("country/<str:code>", country_page, name="country"),
    path("api/teams_list", add_team_to_lists_api, name="teams_list"),
    path("api/leagues_list", add_league_to_lists_api, name="leagues_list"),
    path("api/<str:class_name>/<int:pk>/follow", follow_api, name="follow_api"),
    path(
        "api/<str:class_name>/autocomplete", autocomplete_api, name="autocomplete_api"
    ),
    path("user/<str:username>", ProfileView.as_view(), name="user"),
    path("terms", terms_page, name="terms"),
    path("map", map_page, name="map"),
    path("team", ParseTeamView.as_view(), name="team_parse"),
    path("league", ParseLeagueView.as_view(), name="league_parse"),
    path("export/athletes", athletes_export_api, name="athletes_export"),
    path("login", login_page, name="login"),
    path("logout", logout_page, name="logout"),
]

templates/_athlete.html
{% load static %}
{% load i18n %}
{% load humanize %}
{% load core_tags %}

<div class="athlete-page container mt-9">
    <div class="row">
        <div class="col-sm-4 float-left">
            {{ athlete.photo_preview }}
            <div class="mt-3">
                <a href="{% url 'core:follow_api' 'athlete' athlete.pk %}" id="subscribe-link{{ sufix }}" class="subscribe-link btn {% if athlete.subscribed %}btn-success{% else %}btn-light{% endif %}" data-hover="{% trans 'Unfollow' %}" data-subscribed="{% trans 'Following' %}" data-unsubscribed="{% trans 'Follow' %}">
                    {% if athlete.subscribed %}{% trans "Following" %}{% else %}{% trans "Follow" %}{% endif %}
                </a>
                <form action="{% url 'core:athletes_list' %}" class="athletes_lists_form mt-3">
                    {% csrf_token %}
                    <input type="number" name="athlete" class="d-none" value="{{ athlete.id }}">
                    <label for="athletes_lists">{% trans "Is part of lists" %}:</label>
                    <select multiple name="athletes_lists" id="athletes_lists" class="form-control select2">
                        {% for athletes_list in athlete.user_athletes_lists %}
                            <option {% if athletes_list.selected %}selected{% endif %} value="{{ athletes_list.pk }}">{{ athletes_list.name }}</option>
                        {% endfor %}
                    </select>
                </form>
            </div>
        </div>
        <div class="col-sm-8 float-right">
            <h1>{{ athlete.name }}</h1>
            <p>{% trans "Category" %}: {{ athlete.category }}</p>
            <p>{% trans "Gender" %}: {{ athlete.get_gender_display }}</p>
            <p>{% trans "Date of Birth (Age)" %}: {{ athlete.birthday }} ({{ athlete.age }})</p>
            <p>{% trans "Place of Birth" %}: {% if athlete.domestic_market %}<a href="{% url 'core:country' athlete.domestic_market %}"><i class="flag flag-{{ athlete.domestic_market|lower }}"></i> {{ athlete.get_domestic_market_display }}</a>{% endif %}</p>
            <p>{% trans "Team" %}: {% if athlete.team_model %}<a href="{% url 'core:team' athlete.team_model.pk %}">{{ athlete.team }}</a>{% else %}{{ athlete.team }}{% endif %}</p>
            <p>{% trans "Location" %}: {% if athlete.location_market %}<a href="{% url 'core:country' athlete.location_market %}"><i class="flag flag-{{ athlete.location_market|lower }}"></i> {{ athlete.get_location_market_display }}</a>{% endif %}</p>
            <p>{% trans "Marketability" %}: {{ athlete.marketability }}</p>
            <p>{% trans "International" %}: {{ athlete.international }}</p>
            <p>{% trans "Website" %}: {% if athlete.website %}<a href="{{ athlete.website }}" target="_blank" rel="noopener">{{ athlete.website }}</a>{% endif %}</p>
            <div>
                {% if athlete.twitter_info %}
                    <a href="https://twitter.com/{{ athlete.twitter_info|get_item:'screen_name' }}" target="_blank"><img class="icon" src="{% static 'img/twitter.svg' %}" alt="twitter"></a>
                    <span class="badge">{{ athlete.twitter_info|get_item:'followers_count'|intcomma }}</span>
                    {% if athlete.twitter_trend_date %}
                        {% if athlete.twitter_trend > 0 %}<spam class="text-success">↑</spam>{% elif athlete.twitter_trend < 0 %}<spam class="text-danger">↓</spam>{% endif %}<span class="badge" data-trend-date="{{ athlete.twitter_trend_date }}">{% if athlete.twitter_trend != 0 %}{{ athlete.twitter_trend|stringformat:"+.1f" }}%{% endif %}</span>
                    {% endif %}
                {% endif %}
                {% if athlete.youtube_info %}
                    <a href="https://www.youtube.com/channel/{{ athlete.youtube_info|get_item:"channelId" }}" target="_blank"><img class="icon" src="{% static 'img/youtube.svg' %}" alt="youtube"></a>
                    <span class="badge">{{ athlete.youtube_info|get_item:'subscriberCount'|intcomma }}</span>
                    {% if athlete.youtube_trend_date %}
                        {% if athlete.youtube_trend > 0 %}<spam class="text-success">↑</spam>{% elif athlete.youtube_trend < 0 %}<spam class="text-danger">↓</spam>{% endif %}<span class="badge" data-trend-date="{{ athlete.youtube_trend_date }}">{% if athlete.youtube_trend != 0 %}{{ athlete.youtube_trend|stringformat:"+.1f" }}%{% endif %}</span>
                    {% endif %}
                {% endif %}
                <!--<a href="#" target="_blank"><img class="icon" src="{% static 'img/instagram.svg' %}" alt="instagram"></a>-->
            </div>
        </div>
    </div>
    <div class="row mt-3 mb-5">
        <ul class="nav nav-tabs col-sm-12 mt-3" id="charts" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="youtube-trends-tab" data-toggle="tab" href="#youtube-trends{{ sufix }}" role="tab" aria-controls="youtube trends" aria-selected="true">{% trans "Youtube trends" %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="youtube-stats-tab" data-toggle="tab" href="#youtube-stats{{ sufix }}" role="tab" aria-controls="youtube stats" aria-selected="false">{% trans "Youtube stats" %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="twitter-trends-tab" data-toggle="tab" href="#twitter-trends{{ sufix }}" role="tab" aria-controls="twitter trends" aria-selected="true">{% trans "Twitter trends" %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="twitter-stats-tab" data-toggle="tab" href="#twitter-stats{{ sufix }}" role="tab" aria-controls="twitter stats" aria-selected="false">{% trans "Twitter stats" %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="wiki-trends-tab" data-toggle="tab" href="#wiki-trends{{ sufix }}" role="tab" aria-controls="wiki trends" aria-selected="true">{% trans "Wikipedia trends" %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="wiki-stats-tab" data-toggle="tab" href="#wiki-stats{{ sufix }}" role="tab" aria-controls="wiki stats" aria-selected="false">{% trans "Wikipedia stats" %}</a>
            </li>
        </ul>
        <div class="tab-content col-sm-12" id="charts-content">
            <div class="tab-pane fade show active" id="youtube-trends{{ sufix }}" role="tabpanel" aria-labelledby="youtube-trends-tab">
                <canvas id="youtube-trends-canv{{ sufix }}" width="400" height="200"></canvas>
            </div>
            <div class="tab-pane fade" id="youtube-stats{{ sufix }}" role="tabpanel" aria-labelledby="youtube-stats-tab">
                <canvas id="youtube-stats-canv{{ sufix }}" width="400" height="200"></canvas>
            </div>
            <div class="tab-pane fade" id="twitter-trends{{ sufix }}" role="tabpanel" aria-labelledby="twitter-trends-tab">
                <canvas id="twitter-trends-canv{{ sufix }}" width="400" height="200"></canvas>
            </div>
            <div class="tab-pane fade" id="twitter-stats{{ sufix }}" role="tabpanel" aria-labelledby="twitter-stats-tab">
                <canvas id="twitter-stats-canv{{ sufix }}" width="400" height="200"></canvas>
            </div>
            <div class="tab-pane fade" id="wiki-trends{{ sufix }}" role="tabpanel" aria-labelledby="wiki-trends-tab">
                <canvas id="wiki-trends-canv{{ sufix }}" width="400" height="200"></canvas>
            </div>
            <div class="tab-pane fade" id="wiki-stats{{ sufix }}" role="tabpanel" aria-labelledby="wiki-stats-tab">
                <canvas id="wiki-stats-canv{{ sufix }}" width="400" height="200"></canvas>
            </div>
        </div>
    </div>
</div>

{% include "_youtube_charts.html" with obj=athlete sufix=sufix %}
{% include "_twitter_charts.html" with obj=athlete sufix=sufix %}
{% include "_wiki_charts.html" with obj=athlete sufix=sufix %}
{% include "_follow.html" with sufix=sufix %}

templates/_menu.html
{% load i18n %}
<li class="nav-item {% if request.path == '/' %}active{% endif %}">
  <a href="{% url 'core:home' %}" class="nav-link">{% trans "Features" %}</a>
</li>
<li class="nav-item">
  <a href="#" class="nav-link">{% trans "Pricing" %}</a>
</li>
<li class="nav-item">
  <a href="#" class="nav-link">{% trans "Webinars" %}</a>
</li>
<li class="nav-item">
  <a href="#" class="nav-link">{% trans "Blog" %}</a>
</li>
<li class="nav-item">
  <a href="{% url 'core:terms' %}" class="nav-link">{% trans "Terms of service" %}</a>
</li>
{% if user.is_authenticated %}
<li class="nav-item">
  <a href="{% url 'core:user' user.username %}" class="nav-link">{{ user.username }}</a>
</li>
<li class="nav-item {% if request.path == '/logout' %}active{% endif %}">
  <a href="{% url 'core:logout' %}" class="nav-link">{% trans "Logout" %}</a>
</li>
{% else %}
<li class="nav-item {% if request.path == '/login' %}active{% endif %}">
  <a href="{% url 'core:login' %}" class="nav-link">{% trans "Login" %}</a>
</li>
{% endif %}

templates/athlete.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load humanize %}
{% load core_tags %}

{% block title %}{{ athlete.name }}{% endblock %}

{% block content %}
    {% include "_athlete.html" with athlete=athlete %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% trans "Athletes" %}{% endblock title %}</title>
    <meta name="description" content="{% block description %}{% trans 'Athletes' %}{% endblock description %}"/>

    <link type="text/css" rel="stylesheet" href="{% static 'node_modules/bootstrap/dist/css/bootstrap.min.css' %}"/>
    <link type="text/css" rel="stylesheet" href="{% static 'node_modules/datatables/media/css/jquery.dataTables.min.css' %}"  media="screen,projection"/>
    <link rel="stylesheet" type="text/css" href="{% static 'node_modules/select2/dist/css/select2.min.css' %}"/>
    <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'img/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'img/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'img/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'img/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'img/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'img/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'img/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'img/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'img/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'img/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'img/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">

    <meta name="robots" content="noindex,nofollow" /><!-- TODO[Mike]: Remove for production -->
  </head>

  <body>
    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="{% url 'core:athletes' %}">{% trans "CRM" %}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            {% include "_menu.html" %}
          </ul>
        </div>
      </div>
    </nav>

    {% block content %}{% endblock content %}

    <script type="text/javascript" src="{% static 'node_modules/jquery/dist/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'node_modules/popper.js/dist/umd/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'node_modules/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'node_modules/datatables/media/js/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'node_modules/select2/dist/js/select2.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'node_modules/moment/min/moment.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'node_modules/chart.js/dist/Chart.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.autocomplete.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
    {% block script %}{% endblock script %}
  </body>
</html>

templates/league.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load humanize %}
{% load core_tags %}

{% block title %}{{ league.name }}{% endblock %}

{% block content %}
    <div class="team-page container mt-9">
        <div class="row">
            <div class="col-sm-4 float-left">
                {{ league.photo_preview }}
                <div class=" mt-3">
                    <a href="{% url 'core:follow_api' 'league' league.pk %}" id="subscribe-link" class="subscribe-link btn {% if league.subscribed %}btn-success{% else %}btn-light{% endif %}" data-hover="{% trans 'Unfollow' %}" data-subscribed="{% trans 'Following' %}" data-unsubscribed="{% trans 'Follow' %}">
                        {% if league.subscribed %}{% trans "Following" %}{% else %}{% trans "Follow" %}{% endif %}
                    </a>
                    <form action="{% url 'core:leagues_list' %}" id="teams_lists_form" class="mt-3">
                        {% csrf_token %}
                        <input type="number" name="league" class="d-none" value="{{ league.id }}">
                        <label for="leagues_lists">{% trans "Is part of lists" %}:</label>
                        <select multiple name="leagues_lists" id="leagues_lists" class="form-control select2">
                            {% for league_list in league.user_league_lists %}
                                <option {% if league_list.selected %}selected{% endif %} value="{{ league_list.pk }}">{{ league_list.name }}</option>
                            {% endfor %}
                        </select>
                    </form>
                </div>
            </div>
            <div class="col-sm-8 float-right">
                <h1 class="mb-3">{{ league.name }}</h1>
                <p>{% trans "Category" %}: {{ league.category }}</p>
                <p>{% trans "Gender" %}: {{ league.get_gender_display }}</p>
                <p>{% trans "Location" %}: {% if league.location_market %}<a href="{% url 'core:country' league.location_market %}"><i class="flag flag-{{ league.location_market|lower }}"></i> {{ league.get_location_market_display }}</a>{% endif %}</p>
                <p>{% trans "Website" %}: {% if league.website %}<a href="{{ league.website }}" target="_blank" rel="noopener">{{ league.website }}</a>{% endif %}</p>
                <div>
                    {% if league.twitter_info %}
                        <a href="https://twitter.com/{{ league.twitter_info|get_item:'screen_name' }}" target="_blank"><img class="icon" src="{% static 'img/twitter.svg' %}" alt="twitter"></a>
                        <span class="badge">{{ league.twitter_info|get_item:'followers_count'|intcomma }}</span>
                        {% if league.twitter_trend_date %}
                            {% if league.twitter_trend > 0 %}<spam class="text-success">↑</spam>{% elif league.twitter_trend < 0 %}<spam class="text-danger">↓</spam>{% endif %}<span class="badge" data-trend-date="{{ league.twitter_trend_date }}">{% if league.twitter_trend != 0 %}{{ league.twitter_trend|stringformat:"+.1f" }}%{% endif %}</span>
                        {% endif %}
                    {% endif %}
                    {% if league.youtube_info %}
                        <a href="https://www.youtube.com/channel/{{ league.youtube_info|get_item:'channelId' }}" target="_blank"><img class="icon" src="{% static 'img/youtube.svg' %}" alt="youtube"></a>
                        <span class="badge">{{ league.youtube_info|get_item:'subscriberCount'|intcomma }}</span>
                        {% if league.youtube_trend_date %}
                            {% if league.youtube_trend > 0 %}<spam class="text-success">↑</spam>{% elif league.youtube_trend < 0 %}<spam class="text-danger">↓</spam>{% endif %}<span class="badge" data-trend-date="{{ league.youtube_trend_date }}">{% if league.youtube_trend != 0 %}{{ league.youtube_trend|stringformat:"+.1f" }}%{% endif %}</span>
                        {% endif %}
                    {% endif %}
                    <!--<a href="#" target="_blank"><img class="icon" src="{% static 'img/instagram.svg' %}" alt="instagram"></a>-->
                </div>
            </div>
        </div>
        <div class="row mt-3 mb-5">
            <ul class="nav nav-tabs col-sm-12 mt-3" id="charts" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="teams-tab" data-toggle="tab" href="#teams" role="tab" aria-controls="teams" aria-selected="true">{% trans "Teams" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="youtube-trends-tab" data-toggle="tab" href="#youtube-trends" role="tab" aria-controls="youtube trends" aria-selected="true">{% trans "Youtube trends" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="youtube-stats-tab" data-toggle="tab" href="#youtube-stats" role="tab" aria-controls="youtube stats" aria-selected="false">{% trans "Youtube stats" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="twitter-trends-tab" data-toggle="tab" href="#twitter-trends" role="tab" aria-controls="twitter trends" aria-selected="true">{% trans "Twitter trends" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="twitter-stats-tab" data-toggle="tab" href="#twitter-stats" role="tab" aria-controls="twitter stats" aria-selected="false">{% trans "Twitter stats" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="wiki-trends-tab" data-toggle="tab" href="#wiki-trends" role="tab" aria-controls="wiki trends" aria-selected="true">{% trans "Wikipedia trends" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="wiki-stats-tab" data-toggle="tab" href="#wiki-stats" role="tab" aria-controls="wiki stats" aria-selected="false">{% trans "Wikipedia stats" %}</a>
                </li>
                {% if league.get_awis_stats %}
                    <li class="nav-item">
                        <a class="nav-link" id="similarweb-stats-tab" data-toggle="tab" href="#similarweb-stats" role="tab" aria-controls="similarweb stats" aria-selected="false">{% trans "Site visits" %}</a>
                    </li>
                {% endif %}
            </ul>
            <div class="tab-content col-sm-12" id="charts-content">
                <div class="tab-pane fade show active" id="teams" role="tabpanel" aria-labelledby="teams-tab">
                    <ul class="mt-2">
                        {% for team in teams %}
                            <li><a href="{% url 'core:team' team.pk %}">{{ team.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="tab-pane fade show" id="youtube-trends" role="tabpanel" aria-labelledby="youtube-trends-tab">
                    <canvas id="youtube-trends-canv" width="400" height="200"></canvas>
                </div>
                <div class="tab-pane fade" id="youtube-stats" role="tabpanel" aria-labelledby="youtube-stats-tab">
                    <canvas id="youtube-stats-canv" width="400" height="200"></canvas>
                </div>
                <div class="tab-pane fade" id="twitter-trends" role="tabpanel" aria-labelledby="twitter-trends-tab">
                    <canvas id="twitter-trends-canv" width="400" height="200"></canvas>
                </div>
                <div class="tab-pane fade" id="twitter-stats" role="tabpanel" aria-labelledby="twitter-stats-tab">
                    <canvas id="twitter-stats-canv" width="400" height="200"></canvas>
                </div>
                <div class="tab-pane fade" id="wiki-trends" role="tabpanel" aria-labelledby="wiki-trends-tab">
                    <canvas id="wiki-trends-canv" width="400" height="200"></canvas>
                </div>
                <div class="tab-pane fade" id="wiki-stats" role="tabpanel" aria-labelledby="wiki-stats-tab">
                    <canvas id="wiki-stats-canv" width="400" height="200"></canvas>
                </div>
                {% if league.get_awis_stats %}
                    <div class="tab-pane fade" id="similarweb-stats" role="tabpanel" aria-labelledby="similarweb-stats-tab">
                        <canvas id="similarweb-stats-canv" width="400" height="200"></canvas>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    {% include "_youtube_charts.html" with obj=league %}
    {% include "_twitter_charts.html" with obj=league %}
    {% include "_wiki_charts.html" with obj=league %}
    {% include "_awis_charts.html" with obj=league %}
    {% include "_follow.html" %}
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load i18n %}
{% load widget_tweaks %}

{% block title %}{% trans "Login" %}{% endblock %}
{% block description %}{% trans "Login to get access" %}{% endblock description %}

{% block content %}
  <div class="container mt-6">
    <h1 class="text-center">{% trans "Login" %}</h1>

    <div class="row mt-3">
      <form action="{% url 'core:login' %}" method="post" class="col-sm-10 col-md-8 col-lg-6 offset-sm-1 offset-md-2 offset-lg-3">
        <div class="">
          {% csrf_token %}
          {% for field in form %}
            <div class="form-group row">
              <label class="col-sm-3 col-form-label" for="{{ field.auto_id }}">{{ field.label }}</label>
              <div class="col-sm-9">
                {{ field|add_class:"form-control" }}
                {% if field.errors %}
                  <div class="alert alert-warning" role="alert">
                    {{ field.errors }}
                  </div>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          {% if form.non_field_errors %}
            <div class="alert alert-warning col-sm-11 col-md-10 col-lg-9 offset-sm-1 offset-md-2 offset-lg-3" role="alert">
              {{ form.non_field_errors }}
            </div>
          {% endif %}
          <div class="form-group row">
            <div class="col-sm-12">
              <button type="submit" class="btn btn-primary float-right">{% trans "Log in" %}</button>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock content %}

templates/map.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "Map" %}{% endblock title %}

{% block content %}

<svg id="map" class="mt-9" version="1.1" viewBox="0 0 1000 700">
    <g>
        {% for country in countries %}
	        <path id="{{ country.id }}" title="{{ country.total }} {{ country.title }}" fill-opacity="{{ country.opacity }}" data-toggle="tooltip" data-placement="right" d="{{ country.d }}"/>
        {% endfor %}
    </g>
</svg>
{% endblock content %}